baseURL = "https://example.com"
languageCode = "en-us"
title = "Nooraizad Zailani"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 5 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
publishDir = "deploy"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

[author]
	name = "Nooraizad Zailani"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "my personal space"

    showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "mailto:nooraizad57@gmail.com"
    facebook = "https://www.facebook.com/nooraizadzailani"
    twitter = "https://twitter.com/nooraizad"
	instagram = "https://www.instagram.com/nooraizad/"
	linkedin = "https://www.linkedin.com/in/muhammad-nooraizad-zailani/"

	# Programming
    github = "https://github.com/nooraizad"


# Menu links along the sidebar navigation.




# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true