baseURL = "https://nooraizad.github.io"
languageCode = "en-us"
title = "nooraizad"
theme = "hugo-theme-noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
publishDir = "nooraizad.github.io"

[taxonomies]
  tag = "tags"

[author]
	name = "kimcc"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "my personal blog"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "#"
    facebook = "#"
    twitter = "#"
	instagram = "#"
	tumblr = "#"
	reddit = "#"
	pinterest = "#"
	youtube = "#"
	weibo = "#"
	vk = "#"
	linkedin = "#"

	# Writing
    medium = "#"
	blogger = "#"
	wordpress = "#"

	# Creative & Visual
    dribbble = "#"
	behance = "#"
	deviantart = "#"
	flickr = "#"

	# Programming
    github = "#"
	stackoverflow = "#"
	gitlab = "#"
	codepen = "#"



# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true